function B = ControlMatrix(obj,in2,in3,dt,in5)
%ControlMatrix
%    B = ControlMatrix(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/05/15 18:41:49

L2 = in5(:,3);
L3 = in5(:,5);
Lt1 = in5(:,2);
Lt2 = in5(:,4);
distance = in5(:,1);
slip_left = in5(:,7);
slip_right = in5(:,6);
x3 = in2(3,:);
x6 = in2(6,:);
x9 = in2(9,:);
t2 = cos(x3);
t3 = cos(x6);
t4 = cos(x9);
t5 = sin(x3);
t6 = sin(x6);
t7 = sin(x9);
t8 = 1.0./L2;
t9 = 1.0./L3;
t10 = 1.0./distance;
t11 = slip_left-1.0;
t12 = slip_right-1.0;
t13 = -x6;
t14 = -x9;
t15 = slip_left./2.0;
t16 = slip_right./2.0;
t17 = t13+x3;
t18 = t14+x6;
t23 = t15-1.0./2.0;
t24 = t16-1.0./2.0;
t19 = cos(t17);
t20 = cos(t18);
t21 = sin(t17);
t22 = sin(t18);
t25 = t19.*t23;
t26 = t19.*t24;
t27 = t21.*t23;
t28 = t21.*t24;
t29 = (Lt1.*t10.*t11.*t19)./2.0;
t30 = (Lt1.*t10.*t12.*t19)./2.0;
t31 = (Lt1.*t10.*t11.*t21)./2.0;
t32 = (Lt1.*t10.*t12.*t21)./2.0;
t33 = -t30;
t34 = -t31;
t35 = t27+t29;
t36 = t26+t32;
t37 = t25+t34;
t38 = t28+t33;
t39 = t20.*t36;
t41 = Lt2.*t8.*t22.*t35;
t40 = t20.*t37;
t42 = Lt2.*t8.*t22.*t38;
t43 = t40+t41;
t44 = t39+t42;
B = reshape([-dt.*t2.*t24,-dt.*t5.*t24,dt.*t10.*t12.*(-1.0./2.0),-dt.*t3.*t36,-dt.*t6.*t36,-dt.*t8.*t38,-dt.*t4.*t44,-dt.*t7.*t44,-dt.*t9.*(t22.*t36-(Lt2.*t10.*t12.*t20)./2.0),-dt.*t2.*t23,-dt.*t5.*t23,(dt.*t10.*t11)./2.0,-dt.*t3.*t37,-dt.*t6.*t37,-dt.*t8.*t35,-dt.*t4.*t43,-dt.*t7.*t43,-dt.*t9.*(t22.*t37+(Lt2.*t10.*t11.*t20)./2.0)],[9,2]);
end
