function B = ControlMatrix(obj,in2,in3,dt,in5)
%ControlMatrix
%    B = ControlMatrix(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/05/15 09:42:20

L2 = in5(:,3);
L3 = in5(:,5);
Lt1 = in5(:,2);
Lt2 = in5(:,4);
d = in5(:,1);
x3 = in2(3,:);
x6 = in2(6,:);
x9 = in2(9,:);
t2 = cos(x3);
t3 = cos(x6);
t4 = cos(x9);
t5 = sin(x3);
t6 = sin(x6);
t7 = sin(x9);
t8 = 1.0./L2;
t9 = 1.0./L3;
t10 = 1.0./d;
t11 = -x6;
t12 = -x9;
t13 = dt.*t10;
t14 = t11+x3;
t15 = t12+x6;
t20 = (dt.*t2)./2.0;
t21 = (dt.*t5)./2.0;
t16 = cos(t14);
t17 = cos(t15);
t18 = sin(t14);
t19 = sin(t15);
t22 = t16./2.0;
t23 = t18./2.0;
t24 = Lt1.*t10.*t16;
t25 = Lt2.*t10.*t17;
t26 = Lt1.*t10.*t18;
t27 = -t24;
t28 = -t26;
t29 = t22+t26;
t30 = t23+t24;
t31 = t22+t28;
t32 = t23+t27;
t33 = t17.*t29;
t35 = Lt2.*t8.*t19.*t30;
t34 = t17.*t31;
t36 = Lt2.*t8.*t19.*t32;
t37 = t33+t36;
t38 = t34+t35;
B = reshape([t20,t21,t13,dt.*t3.*t29,dt.*t6.*t29,dt.*t8.*t32,dt.*t4.*t37,dt.*t7.*t37,-dt.*t9.*(t25-t19.*t29),t20,t21,-t13,dt.*t3.*t31,dt.*t6.*t31,dt.*t8.*t30,dt.*t4.*t38,dt.*t7.*t38,dt.*t9.*(t25+t19.*t31)],[9,2]);
end
