function f = Function(obj,in2,in3,dt,in5)
%Function
%    F = Function(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/05/15 09:42:21

L2 = in5(:,3);
L3 = in5(:,5);
Lt1 = in5(:,2);
Lt2 = in5(:,4);
d = in5(:,1);
u1 = in3(1,:);
u2 = in3(2,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
x5 = in2(5,:);
x6 = in2(6,:);
x7 = in2(7,:);
x8 = in2(8,:);
x9 = in2(9,:);
t2 = 1.0./L2;
t3 = 1.0./d;
t4 = -u2;
t5 = -x6;
t6 = -x9;
t7 = u1./2.0;
t8 = u2./2.0;
t9 = t4+u1;
t10 = t5+x3;
t11 = t6+x6;
t16 = t7+t8;
t12 = cos(t10);
t13 = cos(t11);
t14 = sin(t10);
t15 = sin(t11);
t17 = Lt1.*t3.*t9.*t12;
t18 = Lt1.*t3.*t9.*t14;
t19 = t12.*t16;
t20 = t14.*t16;
t22 = t18+t19;
t25 = -Lt2.*t2.*t15.*(t17-t20);
t24 = t13.*t22;
t26 = t24+t25;
f = [x1+dt.*t16.*cos(x3);x2+dt.*t16.*sin(x3);x3+dt.*t3.*t9;x4+dt.*t22.*cos(x6);x5+dt.*t22.*sin(x6);x6-dt.*t2.*(t17-t20);x7+dt.*t26.*cos(x9);x8+dt.*t26.*sin(x9);x9+(dt.*(t15.*t22-Lt2.*t3.*t9.*t13))./L3];
end
