function f = Function(obj,in2,in3,dt,in5)
%Function
%    F = Function(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/05/15 18:41:49

L2 = in5(:,3);
L3 = in5(:,5);
Lt1 = in5(:,2);
Lt2 = in5(:,4);
distance = in5(:,1);
slip_left = in5(:,7);
slip_right = in5(:,6);
u1 = in3(1,:);
u2 = in3(2,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
x5 = in2(5,:);
x6 = in2(6,:);
x7 = in2(7,:);
x8 = in2(8,:);
x9 = in2(9,:);
t2 = 1.0./L2;
t3 = 1.0./distance;
t4 = slip_left-1.0;
t5 = slip_right-1.0;
t6 = -x6;
t7 = -x9;
t8 = t4.*u2;
t9 = t5.*u1;
t10 = t6+x3;
t11 = t7+x6;
t12 = cos(t10);
t13 = cos(t11);
t14 = sin(t10);
t15 = sin(t11);
t16 = -t9;
t17 = t8./2.0;
t18 = t9./2.0;
t19 = t8+t16;
t20 = t17+t18;
t21 = t12.*t20;
t22 = t14.*t20;
t23 = (Lt1.*t3.*t12.*t19)./2.0;
t24 = (Lt1.*t3.*t14.*t19)./2.0;
t25 = -t24;
t26 = t22+t23;
t27 = t21+t25;
t29 = Lt2.*t2.*t15.*t26;
t28 = t13.*t27;
t30 = t28+t29;
f = [x1-dt.*t20.*cos(x3);x2-dt.*t20.*sin(x3);x3+(dt.*t3.*t19)./2.0;x4-dt.*t27.*cos(x6);x5-dt.*t27.*sin(x6);x6-dt.*t2.*t26;x7-dt.*t30.*cos(x9);x8-dt.*t30.*sin(x9);x9-(dt.*(t15.*t27+(Lt2.*t3.*t13.*t19)./2.0))./L3];
end
