function B = ControlMatrix(obj,in2,in3,dt,in5)
%ControlMatrix
%    B = ControlMatrix(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    30-Jun-2023 03:39:07

slip_left = in5(:,2);
slip_right = in5(:,1);
wheel_distance = in5(:,3);
x3 = in2(3,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = 1.0./wheel_distance;
t5 = slip_left./2.0;
t6 = slip_right./2.0;
t7 = t5-1.0./2.0;
t8 = t6-1.0./2.0;
B = reshape([-dt.*t2.*t8,-dt.*t3.*t8,dt.*t4.*(slip_right-1.0).*(-1.0./2.0),-dt.*t2.*t7,-dt.*t3.*t7,(dt.*t4.*(slip_left-1.0))./2.0],[3,2]);
