function f = Function(obj,in2,in3,dt,in5)
%Function
%    F = Function(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    30-Jun-2023 03:39:07

slip_left = in5(:,2);
slip_right = in5(:,1);
u1 = in3(1,:);
u2 = in3(2,:);
wheel_distance = in5(:,3);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
t2 = slip_left-1.0;
t3 = slip_right-1.0;
t4 = (t2.*u2)./2.0;
t5 = (t3.*u1)./2.0;
t6 = t4+t5;
f = [x1-dt.*t6.*cos(x3);x2-dt.*t6.*sin(x3);x3+(dt.*(t2.*u2-t3.*u1))./(wheel_distance.*2.0)];
