function A = SystemMatrix(obj,in2,in3,dt,in5)
%SystemMatrix
%    A = SystemMatrix(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    30-Jun-2023 03:39:06

slip_left = in5(:,2);
slip_right = in5(:,1);
u1 = in3(1,:);
u2 = in3(2,:);
x3 = in2(3,:);
t2 = slip_left-1.0;
t3 = slip_right-1.0;
t4 = (t2.*u2)./2.0;
t5 = (t3.*u1)./2.0;
t6 = t4+t5;
A = reshape([1.0,0.0,0.0,0.0,1.0,0.0,dt.*t6.*sin(x3),-dt.*t6.*cos(x3),1.0],[3,3]);
