function B_d = B_d_num_ext(in1,in2,in3)
%B_D_NUM_EXT
%    B_D = B_D_NUM_EXT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Sep-2020 16:33:07

h = in3(:,2);
l = in3(:,1);
x_lin3 = in1(3,:);
x_lin4 = in1(4,:);
x_lin5 = in1(5,:);
t2 = cos(x_lin3);
t3 = sin(x_lin3);
t4 = 1.0./l;
t5 = x_lin4-1.0;
t6 = x_lin5-1.0;
B_d = reshape([h.*t2.*t5.*(-1.0./2.0),h.*t3.*t5.*(-1.0./2.0),h.*t4.*t5.*(-1.0./2.0),0.0,0.0,h.*t2.*t6.*(-1.0./2.0),h.*t3.*t6.*(-1.0./2.0),(h.*t4.*t6)./2.0,0.0,0.0],[5,2]);
