function f_d = f_d_num_ext(in1,in2,in3)
%F_D_NUM_EXT
%    F_D = F_D_NUM_EXT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Sep-2020 16:33:07

h = in3(:,2);
l = in3(:,1);
u_k1 = in2(1,:);
u_k2 = in2(2,:);
x_k1 = in1(1,:);
x_k2 = in1(2,:);
x_k3 = in1(3,:);
x_k4 = in1(4,:);
x_k5 = in1(5,:);
t2 = x_k4-1.0;
t3 = x_k5-1.0;
t4 = t2.*u_k1;
t5 = t3.*u_k2;
t6 = t4+t5;
f_d = [x_k1-(h.*t6.*cos(x_k3))./2.0;x_k2-(h.*t6.*sin(x_k3))./2.0;x_k3-(h.*(t4-t5))./(l.*2.0);x_k4;x_k5];
