function f = Function(obj,in2,in3,dt,in5)
%Function
%    F = Function(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Jul-2023 16:42:30

length_back = in5(:,2);
length_front = in5(:,1);
slip_left = in5(:,4);
slip_right = in5(:,3);
u1 = in3(1,:);
u2 = in3(2,:);
wheel_distance = in5(:,5);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
x5 = in2(5,:);
x6 = in2(6,:);
t2 = cos(x6);
t3 = sin(x6);
t4 = 1.0./length_front;
t5 = slip_left-1.0;
t6 = slip_right-1.0;
t7 = 1.0./wheel_distance;
t8 = -x6;
t9 = t5.*u2;
t10 = t6.*u1;
t11 = t8+x3;
t12 = cos(t11);
t13 = sin(t11);
t14 = -t10;
t15 = t9./2.0;
t16 = t10./2.0;
t17 = t9+t14;
t18 = t15+t16;
f = [x1-dt.*t18.*cos(x3);x2-dt.*t18.*sin(x3);x3+(dt.*t7.*t17)./2.0;x4-dt.*(t2.*t12.*t18-(length_back.*t2.*t7.*t13.*t17)./2.0);x5-dt.*(t3.*t12.*t18-(length_back.*t3.*t7.*t13.*t17)./2.0);x6-dt.*(t4.*t13.*t18+(length_back.*t4.*t7.*t12.*t17)./2.0)];
