function A = SystemMatrix(obj,in2,in3,dt,in5)
%SystemMatrix
%    A = SystemMatrix(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Jul-2023 16:42:29

length_back = in5(:,2);
length_front = in5(:,1);
slip_left = in5(:,4);
slip_right = in5(:,3);
u1 = in3(1,:);
u2 = in3(2,:);
wheel_distance = in5(:,5);
x3 = in2(3,:);
x6 = in2(6,:);
t2 = cos(x6);
t3 = sin(x6);
t4 = 1.0./length_front;
t5 = slip_left-1.0;
t6 = slip_right-1.0;
t7 = 1.0./wheel_distance;
t8 = -x6;
t9 = t5.*u2;
t10 = t6.*u1;
t11 = t8+x3;
t12 = cos(t11);
t13 = sin(t11);
t14 = -t10;
t15 = t9./2.0;
t16 = t10./2.0;
t17 = t9+t14;
t18 = t15+t16;
t19 = t2.*t13.*t18;
t20 = t3.*t13.*t18;
t21 = t4.*t12.*t18;
t22 = (length_back.*t2.*t7.*t12.*t17)./2.0;
t23 = (length_back.*t3.*t7.*t12.*t17)./2.0;
t24 = (length_back.*t4.*t7.*t13.*t17)./2.0;
t25 = -t24;
t26 = t21+t25;
t27 = dt.*t26;
A = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,dt.*t18.*sin(x3),-dt.*t18.*cos(x3),1.0,dt.*(t19+t22),dt.*(t20+t23),-t27,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-dt.*(t19+t22-t3.*t12.*t18+(length_back.*t3.*t7.*t13.*t17)./2.0),-dt.*(t20+t23+t2.*t12.*t18-(length_back.*t2.*t7.*t13.*t17)./2.0),t27+1.0],[6,6]);
