function B = ControlMatrix(obj,in2,in3,dt,length_base)
%ControlMatrix
%    B = ControlMatrix(OBJ,IN2,IN3,DT,LENGTH_BASE)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Jun-2023 19:39:48

x3 = in2(3,:);
x4 = in2(4,:);
B = reshape([dt.*cos(x3),dt.*sin(x3),(dt.*tan(x4))./length_base,0.0,0.0,0.0,0.0,dt],[4,2]);
