function f = Function(obj,in2,in3,dt,length_base)
%Function
%    F = Function(OBJ,IN2,IN3,DT,LENGTH_BASE)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Jun-2023 19:39:48

u1 = in3(1,:);
u2 = in3(2,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
f = [x1+dt.*u1.*cos(x3);x2+dt.*u1.*sin(x3);x3+(dt.*u1.*tan(x4))./length_base;x4+dt.*u2];
