function A = SystemMatrix(obj,in2,in3,dt,length_base)
%SystemMatrix
%    A = SystemMatrix(OBJ,IN2,IN3,DT,LENGTH_BASE)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Jun-2023 19:39:48

u1 = in3(1,:);
x3 = in2(3,:);
x4 = in2(4,:);
A = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-dt.*u1.*sin(x3),dt.*u1.*cos(x3),1.0,0.0,0.0,0.0,(dt.*u1.*(tan(x4).^2+1.0))./length_base,1.0],[4,4]);
