function A_d = A_d_num(in1,in2,in3)
%A_D_NUM
%    A_D = A_D_NUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Oct-2020 18:59:14

h = in3(:,2);
u_lin1 = in2(1,:);
u_lin2 = in2(2,:);
x_lin3 = in1(3,:);
t2 = u_lin1+u_lin2;
A_d = reshape([1.0,0.0,0.0,0.0,1.0,0.0,h.*t2.*sin(x_lin3).*(-1.0./2.0),(h.*t2.*cos(x_lin3))./2.0,1.0],[3,3]);
