function B_d = B_d_num(in1,in2,in3)
%B_D_NUM
%    B_D = B_D_NUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Oct-2020 18:59:14

h = in3(:,2);
l = in3(:,1);
x_lin3 = in1(3,:);
t2 = cos(x_lin3);
t3 = sin(x_lin3);
t4 = 1.0./l;
t5 = (h.*t2)./2.0;
t6 = (h.*t3)./2.0;
t7 = (h.*t4)./2.0;
B_d = reshape([t5,t6,t7,t5,t6,-t7],[3,2]);
