function B_d = B_d_num_slip(in1,in2,in3)
%B_D_NUM_SLIP
%    B_D = B_D_NUM_SLIP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Oct-2020 16:39:50

h = in3(:,2);
i_l = in3(:,4);
i_r = in3(:,3);
l = in3(:,1);
x_lin3 = in1(3,:);
t2 = cos(x_lin3);
t3 = sin(x_lin3);
t4 = i_l-1.0;
t5 = i_r-1.0;
t6 = 1.0./l;
B_d = reshape([h.*t2.*t5.*(-1.0./2.0),h.*t3.*t5.*(-1.0./2.0),h.*t5.*t6.*(-1.0./2.0),h.*t2.*t4.*(-1.0./2.0),h.*t3.*t4.*(-1.0./2.0),(h.*t4.*t6)./2.0],[3,2]);
