function f_d = f_d_num_slip(in1,in2,in3)
%F_D_NUM_SLIP
%    F_D = F_D_NUM_SLIP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Oct-2020 16:39:50

h = in3(:,2);
i_l = in3(:,4);
i_r = in3(:,3);
l = in3(:,1);
u_k1 = in2(1,:);
u_k2 = in2(2,:);
x_k1 = in1(1,:);
x_k2 = in1(2,:);
x_k3 = in1(3,:);
t2 = i_l-1.0;
t3 = i_r-1.0;
t4 = t2.*u_k2;
t5 = t3.*u_k1;
t6 = t4+t5;
f_d = [x_k1-(h.*t6.*cos(x_k3))./2.0;x_k2-(h.*t6.*sin(x_k3))./2.0;x_k3+(h.*(t4-t5))./(l.*2.0)];
