function f_d = f_d_num(in1,in2,in3)
%F_D_NUM
%    F_D = F_D_NUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Oct-2020 18:59:14

h = in3(:,2);
l = in3(:,1);
u_k1 = in2(1,:);
u_k2 = in2(2,:);
x_k1 = in1(1,:);
x_k2 = in1(2,:);
x_k3 = in1(3,:);
t2 = u_k1+u_k2;
f_d = [x_k1+(h.*t2.*cos(x_k3))./2.0;x_k2+(h.*t2.*sin(x_k3))./2.0;x_k3+(h.*(u_k1-u_k2))./(l.*2.0)];
