function f = f_num(in1,in2,in3)
%F_NUM
%    F = F_NUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Oct-2020 18:59:14

l = in3(:,1);
u1 = in2(1,:);
u2 = in2(2,:);
x3 = in1(3,:);
t2 = u1+u2;
f = [(t2.*cos(x3))./2.0;(t2.*sin(x3))./2.0;(u1-u2)./(l.*2.0)];
