function f = f_num_ext(in1,in2,in3)
%F_NUM_EXT
%    F = F_NUM_EXT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Sep-2020 16:33:06

l = in3(:,1);
u1 = in2(1,:);
u2 = in2(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x4-1.0;
t3 = x5-1.0;
t4 = t2.*u1;
t5 = t3.*u2;
t6 = t4+t5;
f = [t6.*cos(x3).*(-1.0./2.0);t6.*sin(x3).*(-1.0./2.0);((t4-t5).*(-1.0./2.0))./l;0.0;0.0];
